// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pepuncgzxtrgkyfxscsg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBlcHVuY2d6eHRyZ2t5ZnhzY3NnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NjY3NTksImV4cCI6MjA2NDA0Mjc1OX0.du95-71YbllSLGYSrw4sGaAID5mOMy-MrqrBNfApmMQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);